#!/bin/bash
readarray -t versions < <(find trained-model/model -mindepth 1 -maxdepth 1 -type d -printf '%P\n')

# HACK: start with version 10000 instead of 00000 so that bash does not work in octal-number mode
maximum_version="10000"
for n in "${versions[@]}" ; do
    ((n > maximum_version)) && maximum_version=$n
done

next_version=$((maximum_version+1))
printf -v next_version "%05d" $next_version

./training-scripts/train-model.sh $next_version
ERRORCODE=$?
exit $ERRORCODE