#!/usr/bin/env python3

from __future__ import division
from PIL import Image
import math
import os
from os import listdir
from os.path import isfile, join
import argparse
import hashlib
import picture_cutter.cutter

def cut_subimages(picture_path, filename_prefix, output_directory, subimage_definitions):
    print("Opening image '%s'..." % picture_path)
    image = Image.open(picture_path)

    # crop image into subimages
    print("Cutting image into subimages...")
    subimages = picture_cutter.cutter.cut(image, subimage_definitions)

    # save subimages
    for item_key, subimage in subimages.items():
        save_filename = filename_prefix + "_" + str(item_key) + ".jpg"
        save_path = os.path.join(output_directory, save_filename)
        print("Saving subimage to '%s'..." % save_path)
        if not os.path.exists(output_directory):
            os.makedirs(output_directory)

        if os.path.exists(save_path):
            os.remove(save_path)
        subimage.save(save_path)

def sha256sum(filename):
    h  = hashlib.sha256()
    b  = bytearray(128*1024)
    mv = memoryview(b)
    with open(filename, 'rb', buffering=0) as f:
        for n in iter(lambda : f.readinto(mv), 0):
            h.update(mv[:n])
    return h.hexdigest()

def get_subimage_definition(item_number):
    if item_number < 7:
        raise Exception("item number must be at least 7")
    elif 7 <= item_number <= 25:
        # front side
        #side = "front"
        
        # full item
        #left = 194 / 2478
        #right = 2298 / 2478

        # only checkboxes
        left = 1747 / 2480
        right = 2307 / 2480

        item_height = 1632 - 1526 + 0.5
        top = (1316 + (item_number-7)*item_height) / 3507
        bottom = (1316 + (item_number-7+1)*item_height) / 3507
        pass
    elif 26 <= item_number <= 29:
        # back side
        #side = "back"

        # full item
        #left = 284 / 2478
        
        # only checkboxes
        left = (1820+9) / 2480
        right = (2366+16+9) / 2480
        
        item_height = 606 - 504 + 4 + 0.5
        top = (400-1 + (item_number-26)*item_height) / 3507
        bottom = (400-1 + (item_number-26+1)*item_height) / 3507
        pass
    elif item_number > 29:
        raise Exception("item number must be at most 29")
    
    return {
            "item"+str(item_number):  {
                "top": top,
                "bottom": bottom,
                "left": left,
                "right": right
            } 
        }

if __name__ == '__main__':
    print("Generating item pictures from sheet...")

    parser = argparse.ArgumentParser()
    parser.add_argument('--picture')
    parser.add_argument('--side')
    parser.add_argument('--outputdirectory')
    args = parser.parse_args()
    
    probably_unique_id = os.path.basename(args.picture) + "_" + sha256sum(args.picture) + "_" + args.side

    if args.side == 'front':
        item_numbers = range(7, 25 + 1)
    elif args.side == 'back':
        item_numbers = range(26, 29 + 1)
    else:
        raise Exception("that option for side is illegal")

    subimage_definitions = {}
    for item_number in item_numbers:
        subimage_definition = get_subimage_definition(item_number)
        subimage_definitions.update(subimage_definition)

    cut_subimages(
        picture_path = args.picture,
        filename_prefix = probably_unique_id, 
        output_directory = args.outputdirectory,
        subimage_definitions = subimage_definitions
    )

    
    