#!/bin/bash

IMAGE_TO_CLASSIFY="$1"

readarray -t pictures < <(find testing-data -type f)
for picture in "${pictures[@]}"; do
  echo " ==== $picture ==== "
  python testing-scripts/label_image.py \
    --input_mean 0 \
    --input_std 255 \
    --model_file data/mobile_model.tflite \
    --label_file data/class_labels.txt \
    --image "$picture" 2> /dev/null
  echo
done